# Advanced ML Operations Configuration
# =====================================

# Model Registry Settings
model_registry:
  backend: "mlflow"
  tracking_uri: "http://localhost:5000"
  artifact_location: "s3://ml-artifacts-bucket"
  experiment_tracking: true
  model_versioning: true
  automatic_staging: true

# Data Pipeline Configuration
data_pipeline:
  source:
    type: "streaming"
    kafka_brokers: ["localhost:9092"]
    topics: ["ml-features", "ml-labels"]
    batch_size: 1000
    window_size: "10s"
  
  preprocessing:
    scaling: "standard"
    encoding: "one_hot"
    feature_selection: "variance_threshold"
    missing_value_strategy: "median"
  
  validation:
    schema_validation: true
    data_quality_checks: true
    drift_detection: true
    anomaly_detection: true

# Model Training Configuration
training:
  distributed: true
  num_workers: 4
  gpu_enabled: true
  mixed_precision: true
  
  hyperparameter_optimization:
    method: "optuna"
    n_trials: 100
    optimization_direction: "maximize"
    pruning: true
  
  early_stopping:
    patience: 10
    min_delta: 0.001
    monitor: "val_accuracy"

# Deployment Configuration
deployment:
  strategy: "blue_green"
  auto_scaling:
    enabled: true
    min_replicas: 2
    max_replicas: 10
    target_cpu_utilization: 70
  
  monitoring:
    metrics_collection: true
    alerting: true
    log_level: "INFO"
    health_checks: true
  
  security:
    authentication: true
    rate_limiting: true
    encryption_at_rest: true
    encryption_in_transit: true

# Model Monitoring
monitoring:
  performance_tracking:
    accuracy_threshold: 0.85
    latency_threshold_ms: 100
    throughput_threshold: 1000
  
  data_drift:
    detection_method: "ks_test"
    significance_level: 0.05
    window_size: 1000
  
  model_drift:
    detection_method: "psi"
    threshold: 0.2
    monitoring_frequency: "daily"

# A/B Testing Configuration
ab_testing:
  framework: "facebook_planout"
  traffic_allocation: 0.1
  control_group_size: 0.5
  statistical_significance: 0.05
  minimum_sample_size: 1000
  
# Feature Store Configuration
feature_store:
  backend: "feast"
  online_store: "redis"
  offline_store: "parquet"
  registry: "sql"
  feature_versioning: true
  
# Compliance and Governance
governance:
  data_lineage_tracking: true
  model_explainability: true
  bias_detection: true
  privacy_preservation: true
  audit_logging: true
