name: ML Training Pipeline for time being 

on:
  push:
    branches: [ "main" ]
    paths:
      - 'ML_Implementation/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'ML_Implementation/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install ruff pylint flake8
    
    - name: Run linting
      run: |
        ruff check ML_Implementation/
        pylint ML_Implementation/src/
        flake8 ML_Implementation/src/

  train:
    needs: lint
    runs-on: self-hosted  # For GPU access
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build ML Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./ML_Implementation
        file: ./ML_Implementation/Dockerfile
        push: false
        load: true
        tags: ml-emotion:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Train Model
      run: |
        docker run --gpus all \
          -v ${PWD}/ML_Implementation/data:/app/data \
          -v ${PWD}/ML_Implementation/models:/app/models \
          -v ${PWD}/ML_Implementation/logs:/app/logs \
          ml-emotion:latest
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ml-artifacts
        path: |
          ML_Implementation/models/final_model/
          ML_Implementation/logs/
          ML_Implementation/data/processed/
    
    - name: Cleanup
      if: always()
      run: |
        docker rmi ml-emotion:latest || true
        docker system prune -f 