name: ML Workflow Pipeline

on:
  push:
    branches: [ "main", "feature/*" ]  # Runs on pushes to main & feature branches
  pull_request:
    branches: [ "main" ]  # Runs on PRs to main

jobs:
  lint:
    name: Linting Stage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Linting Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint ruff

    - name: Run Pylint
      continue-on-error: true  # Don't fail the pipeline if linting fails
      run: |
        pylint ML_Implementation/src/

    - name: Run Ruff Formatter
      continue-on-error: true
      run: |
        ruff format ML_Implementation/

    - name: Run Ruff Linter
      continue-on-error: true
      run: |
        ruff check ML_Implementation/

    - name: Run Ruff Lint with Delta Output
      continue-on-error: true
      run: |
        ruff check --output-format=delta ML_Implementation/

    - name: Run TextProto Syntax Check
      continue-on-error: true
      run: |
        find ML_Implementation/ -name "*.proto" -exec cat {} \; || echo "No .proto files found"

    - name: Debug Test Directory
      run: ls -lahR ML_Implementation/tests/ || echo "Test directory not found!"
      
    
  unittest:
    name: Unit Testing Stage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Test Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest numpy

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Debug Test Discovery
      run: pytest ML_Implementation/tests --collect-only --verbose

    - name: Run Unit Tests
      run: pytest ML_Implementation/tests --junitxml=ML_Implementation/tests/unittest-results.xml --verbose --capture=sys || true

    - name: Debug Test Results Directory
      run: ls -lah ML_Implementation/tests/ || echo "Test results directory not found!"

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-results
        path: ML_Implementation/tests/




  all_test_results:
    name: Collect All Test Results
    runs-on: ubuntu-latest

    steps:
    - name: List Available Artifacts
      run: ls -lah

    - name: Download Unit Test Results
      uses: actions/download-artifact@v4
      with:
        name: unit-test-results
        path: ML_Implementation/tests/

    - name: Debug Downloaded Files
      run: ls -lah ML_Implementation/tests/ || echo "Artifact download failed!"

    - name: Display Test Results
      run: cat ML_Implementation/tests/unittest-results.xml || echo "No test results found!"

    - name: Final Status
      run: echo "All stages executed! 🚀"
    
