name: ML Workflow Pipeline

on:
  push:
    branches: [ "main", "feature/*" ]  # Runs on pushes to main & feature branches
  pull_request:
    branches: [ "main" ]  # Runs on PRs to main

jobs:
  lint:
    name: Linting Stage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Linting Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint ruff

    - name: Run Pylint
      run: |
        pylint ML_Implementation/src/ || true  # Avoid failing pipeline on warnings

    - name: Run Ruff Formatter
      run: |
        ruff format ML_Implementation/

    - name: Run Ruff Linter
      run: |
        ruff check ML_Implementation/

    - name: Run Ruff Lint with Delta Output
      run: |
        ruff check --output-format=delta ML_Implementation/

    - name: Run TextProto Syntax Check
      run: |
        find ML_Implementation/ -name "*.proto" -exec cat {} \; || echo "No .proto files found"

  unittest:
    name: Unit Testing Stage
    needs: lint  # Runs after linting stage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Test Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest numpy

    - name: Run Unit Tests
      run: |
        pytest ML_Implementation/tests --junitxml=unittest-results.xml

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: unit-test-results
        path: unittest-results.xml

  all_test_results:
    name: Collect All Test Results
    needs: unittest  # Runs after tests finish
    runs-on: ubuntu-latest

    steps:
    - name: Download Linting and Unit Test Artifacts
      uses: actions/download-artifact@v3

    - name: Display Test Results
      run: |
        cat unit-test-results/unittest-results.xml || echo "No test results found"
    
    - name: Final Status
      run: echo "All tests completed successfully! 🚀"
