name: ML Workflow Pipeline

on:
  push:
    branches: [ "main", "feature/*" ]  # Runs on pushes to main & feature branches
  pull_request:
    branches: [ "main" ]  # Runs on PRs to main

jobs:
  lint:
    name: Linting Stage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Linting Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint ruff

    - name: Run Pylint
      continue-on-error: true  # Don't fail the pipeline if linting fails
      run: |
        pylint ML_Implementation/src/

    - name: Run Ruff Formatter
      continue-on-error: true
      run: |
        ruff format ML_Implementation/

    - name: Run Ruff Linter
      continue-on-error: true
      run: |
        ruff check ML_Implementation/

    - name: Run Ruff Lint with Delta Output
      continue-on-error: true
      run: |
        ruff check --output-format=delta ML_Implementation/

    - name: Run TextProto Syntax Check
      continue-on-error: true
      run: |
        find ML_Implementation/ -name "*.proto" -exec cat {} \; || echo "No .proto files found"

  unittest:
    name: Unit Testing Stage
    runs-on: ubuntu-latest  # Runs independently of linting

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Test Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit Tests
      run: |
        pytest ML_Implementation/tests --junitxml=unittest-results.xml

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-results
        path: unittest-results.xml

  all_test_results:
    name: Collect All Test Results
    runs-on: ubuntu-latest  # Runs independently of previous jobs

    steps:
    - name: Download Unit Test Results
      uses: actions/download-artifact@v4
      with:
        name: unit-test-results

    - name: Display Test Results
      run: |
        cat unit-test-results/unittest-results.xml || echo "No test results found"
    
    - name: Final Status
      run: echo "All stages executed! 🚀"
